### ISSUE TITLE
Ships gone, NaN in cooking port

### ISSUE THREAD

**Issue by nightblade9** [adamk33n3r/melvor-sailing#1]
**Describe the bug**
I think you released a new version of your mod recently? Here's what I got when I logged in today:

- All my ships are gone (despite getting notification about ships being done)
- When I discovered the cooking port, the percentages list as "NaN"

**To Reproduce**
I honestly don't know for the former issue. For the latter, just check the loot.

**Expected behavior**
It would be great if I can get percentages for the cooking port. Also, the percentage sign seems on the wrong side; for other ports, instead of "65.0%", I see "%65.0"

**Screenshots**
![image](https://github.com/user-attachments/assets/d3751fa2-a2b1-4001-b2b7-0d976fd5cadf)

**Desktop (please complete the following information):**

- OS: Linux (Arch (Manjaro))
- Browser Firefox
- Version 13.0.3 (64-bit)

**Mod Version**
2.0.3

**Additional context**
Great mod, thank you for making it! The new changes are, overall, much more clear and transparent in terms of how gameplay works. I also repurchased the ships, which - as expected? - showed that they were done sailing to their respective locations.

**Comment by adamk33n3r** [comment]
>All my ships are gone (despite getting notification about ships being done)

By this do you just mean you had to purchase them? Because yes, that is expected. Their trips should have still been completed and saved, but I introduced costs to the ships so you will have to pay them.
>When I discovered the cooking port, the percentages list as "NaN"

that is really weird, looks like it's an issue with 99 cooking lol. Other levels work fine but when I set it to 99 it shows the NaN.

Also good catch on the percent sign being on the wrong side :P

**Comment by nightblade9** [comment]
- Yes, I repurchased them and the trips were saved. No problem, thank you for clarifying. 
- I do indeed have level 99 cooking, can confirm.

**Comment by nightblade9** [comment]
Incidentally, I really really like how the fishing port actually gives me stuff from up to fishing level 120, because I have the DLC for that. Check these bad bois out: mystic shark, terrorfish, etc. are all from the expansion:

![image](https://github.com/user-attachments/assets/1a7eb76d-d984-423b-a70e-0a006852dd12)

It's also interesting and possibly a separate bug, that the fish at the bottom appear as 0.00%, yet I got a few of each. Do you want me to open a separate issue for that?

**Comment by adamk33n3r** [comment]
Fixed in https://github.com/adamk33n3r/melvor-sailing/tree/v2.0.4

**Comment by adamk33n3r** [comment]
> It's also interesting and possibly a separate bug, that the fish at the bottom appear as 0.00%, yet I got a few of each. Do you want me to open a separate issue for that?

Well, it's just rounding so it probably still has a smaller chance than `0.00`. could be like `0.000003` or something

**Comment by adamk33n3r** [comment]
But ya, the skill ports grab the skill's products that you have the level for dynamically

**Comment by nightblade9** [comment]
I took a very, very cursory look through your change. Will it break when my cooking level goes over 99? I see a lot of `(99 - req)` and `(99 - level)`.

**Comment by adamk33n3r** [comment]
Ha, technically it won't "break", but it might be incorrectly calculating the chance and making it higher than it should from a gameplay perspective...if you could make a separate issue for looking into skills > 99 i'll take a look. I didn't have the expansions when i was first developing this mod. getting some weird results for mining 110

![image](https://github.com/user-attachments/assets/59e844cb-7342-40f8-bd71-2a87c10de876)

**Comment by nightblade9** [comment]
Issue created. Can confirm that sailing works fine with L99 cooking on 2.0.4 - both the actual loot I got back, and expected loot from checking the treasure chest.

Thank you so much for such a quick turn-around on this! You are amazing.

**Comment by nightblade9** [comment]
Can confirm: I hit L100 cooking today, and the cooking port still looks good. Thank you again!
