### ISSUE TITLE
Unclear results when skill levels are greater than 99

### ISSUE THREAD

**Issue by nightblade9** [adamk33n3r/melvor-sailing#2]
**Describe the bug**
When my skill levels are over 99, things get a little weird.

**To Reproduce**
I don't know yet. You asked me to make this bug :) See: #1 

**Expected behavior**
Sailing loot should operate normally when your skill levels are over 99.

**Desktop (please complete the following information):**

- OS: Linux
- Browser Firefox
- Version 131.0.3

**Mod Version**
2.0.3 and 2.0.4

**Additional context**
Keep up the great work!

**Comment by adamk33n3r** [comment]
This looks better. I changed the hardcoded `99`s to get the value from `skill.maxLevelCap`
![image](https://github.com/user-attachments/assets/98d01c7d-ca92-4df8-89cd-eb23f1d7a215)
