### ISSUE TITLE
I can reliably get loot 2x

### ISSUE THREAD

**Issue by nightblade9** [adamk33n3r/melvor-sailing#3]
**Describe the bug**
When a ship returns, I can get loot twice.

**To Reproduce**
When a ship returns, click the "Collect loot" button really fast. (It's practically 100% reproducible on the mobile app.)

**Expected behavior**
The button should be disabled after the first click.

**Screenshots**
Not possible sadly.

**Desktop (please complete the following information):**

- OS: Linux
- Browser Firefox
- Version Latest (133.0 x64)

**Smartphone (please complete the following information):**

- Device: Motorolla Moto g7
- OS: LineageOS 21 (Android 14)
- Browser Melvor app
- Version Latest

**Mod Version**
No clue, sorry, it wasn't listed.

**Additional context**
Probably a race condition.

**Comment by adamk33n3r** [comment]
Interesting, must be a mobile only thing cause I can't reproduce it on desktop. If I double click as fast as I can, it brings up the popup and closes it. But I'll add some code to disable it. Let me know if it fixes it for you.

**Comment by nightblade9** [comment]
Sorry, my repro steps were deficient. I was thinking about this bug a lot. The correct steps are:

- Wait for a ship to return
- Click the "claim" button to see the pop-up with the spoils
- Click close and quickly click on the green button again.

If you do it fast enough, you'll see the pop-up again, and get a second round of spoils.

**Comment by adamk33n3r** [comment]
Oh! OK that makes a little more sense and I could see that happening. Did the recent update fix the issue though?

**Comment by nightblade9** [comment]
Yep, looks good. Thank you for the quick turn-around!
